name: prithvi-ref-assessment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - geopandas
  - shapely
  - fiona
  - pyogrio
  - gdal
  - rasterio
  - pandas
  - pyarrow
  - pyproj
  - matplotlib
  - folium
  - mapclassify
  - jupyter
  - nbformat
  - nbconvert
  - ipykernel
  - pip
